### ISSUE TITLE
Hello I press jailbreak but no Cydia!?

### ISSUE THREAD

**Issue by KadenT8** [coolstar/Chimera13#2]

**Comment by nqcshady** [comment]
From the readme:
**NOTE: THIS PROJECT IS CURRENTLY ONLY USEFUL FOR END USERS AS A NONCE-SETTER. IT IS INCOMPLETE AND WILL NOT JAILBREAK YOUR DEVICE YET**

**Comment by KadenT8** [comment]
> 

Help?!??

**Comment by brandonsaldan** [comment]
bruh read above you smh my head

**Comment by nqcshady** [comment]
read the readme. not an issue
