### ISSUE TITLE
App is completely black when opened.

### ISSUE THREAD

**Issue by Connor0p76** [coolstar/Chimera13#3]
Hello, I have deployed Chimera13 on my iPhone 11 Pro Max and when I opened it, it is completely black. I can still close out of it, see the time, etc. but I cannot use it.

**Comment by LorenzoPane** [comment]
Please refer to the readme:
> UI WILL BE ADDED LATER BEFORE RELEASE

also
> THIS PROJECT IS CURRENTLY ONLY USEFUL FOR END USERS AS A NONCE-SETTER. IT IS INCOMPLETE AND WILL NOT JAILBREAK YOUR DEVICE YET
