### ISSUE TITLE
Main Storyboard

### ISSUE THREAD

**Issue by Crypto-Light** [coolstar/Chimera13#7]
Why isn't there a main storyboard in the Xcode project like the other chimera?

**Comment by simplelifeeee0** [comment]
You’re not serious? Did you read the README.md
🧐

**Comment by Crypto-Light** [comment]
> You’re not serious? Did you read the README.md
> 🧐

No, sorry, I didn't read that.

**Comment by simplelifeeee0** [comment]
All good, lots of trolls come in here asking dumb questions, but yea just read the README.md it will tell you everything you need to know about this project, ui won’t be added until the end

**Comment by Skittyblock** [comment]
There is actually a main storyboard, which you can find in the app directory. However, this project will be converted to SwiftUI in the future and the storyboard will be removed.

**Comment by Aboood412** [comment]
👌🏽
